package com.wapazock.doozby.Utils;

public enum Codes {
    CONNECTION_ERROR,
    INVALID_USERNAME,
    USERNAME_TAKEN,
    USERNAME_VALID,
    SUCCESS,
    REQUEST_FAILED,
    STORAGE_TOKEN_FETCH_FAILED,
    INVALID_USER_TOKEN
}
